// 2020.04.17 - Victor Dods

#include "sept/NPType.hpp"

namespace sept {

Term_c Term;
NonParametricType_c NonParametricType;
Type_c Type;
NonType_c NonType;
EmptyType_c EmptyType;
VoidType_c VoidType;
TrueType_c TrueType;
FalseType_c FalseType;
Bool_c Bool;
Sint8_c Sint8;
Sint16_c Sint16;
Sint32_c Sint32;
Sint64_c Sint64;
Uint8_c Uint8;
Uint16_c Uint16;
Uint32_c Uint32;
Uint64_c Uint64;
Float32_c Float32;
Float64_c Float64;
BoolType_c BoolType;
Sint8Type_c Sint8Type;
Sint16Type_c Sint16Type;
Sint32Type_c Sint32Type;
Sint64Type_c Sint64Type;
Uint8Type_c Uint8Type;
Uint16Type_c Uint16Type;
Uint32Type_c Uint32Type;
Uint64Type_c Uint64Type;
Float32Type_c Float32Type;
Float64Type_c Float64Type;

//
// Registrations for Data functions
//

SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Term_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(NonType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(NonParametricType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(EmptyType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(VoidType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(TrueType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(FalseType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Bool_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint8_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint16_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint32_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint64_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint8_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint16_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint32_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint64_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Float32_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Float64_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(BoolType_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint8Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint16Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint32Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Sint64Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint8Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint16Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint32Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Uint64Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Float32Type_c)
SEPT_DATA_OPERATOR_EQ_REGISTER_TYPE(Float64Type_c)

} // end namespace sept
